"""employee update

Revision ID: 80f8ffa4d7cf
Revises: 46a8b5ef30b7
Create Date: 2022-07-25 05:59:10.338137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80f8ffa4d7cf'
down_revision = '46a8b5ef30b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_index('username', table_name='employee')
    op.create_unique_constraint(None, 'employee', ['name'])
    op.drop_column('employee', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'employee', type_='unique')
    op.create_index('username', 'employee', ['username'], unique=False)
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###
